### PR TITLE
➕ Add Flutter flair

### PR DESCRIPTION
**Pull request by YazeedAlKhalaf**
Hi Ben,

I am a Flutter Developer. I really use Flutter a lot but when I found out that there was no Flutter flair I **freaked** out and decided to add support for the Flutter flair 🙈✨

Regards,
Yazeed AlKhalaf 🚀

### CODE REVIEW

**Comment by benawad** [comment]
you'll also need to add flutter as a key here https://github.com/benawad/vscode-stories-api for validation

**Comment by YazeedAlKhalaf** [comment]
Okay sure I will 🚀

**Comment by YazeedAlKhalaf** [comment]
@benawad New pull request here to help this pull request [https://github.com/benawad/vscode-stories-api/pull/4](https://github.com/benawad/vscode-stories-api/pull/4)

**Comment by arnav03mehta** [comment]
Maybe add some more flairs like python(logo) and java(logo) while you're at it?

**Comment by stemount** [comment]
@arnav03mehta adding the Python and Java logo can be their own issues so somebody can contribute this and familiarise themselves with this PR. :-)

**Review by stemount — APPROVED** [review]
Sure @YazeedAlKhalaf looks legit. approved!

image

**Comment by arnav03mehta** [comment]
Just wanted to ask what is imgMap in src/main.js and src/ViewStoryPanel.ts and how do I get it for a svg

**Pull request merged**
